### ISSUE TITLE
Unable to locate package python-opengl

### ISSUE THREAD

**Issue by sitexa** [huggingface/deep-rl-class#275] opened 2023-04-07 03:39 UTC
In Unit1, the very beginning, local machine, ubuntu 22.04, python 3.10, conda virtual environment. when I type command:
`sudo apt install python-opengl`, it give me error:
`E: Unable to locate package python-opengl`.
I search on net for help, cannot find any helpful info, always refer to PyOpenGL. Is it the same of python-opengl? I find a package named python3-opengl, is it the same of python-opengl?
If it is only me encounter this kind of problem? 
Any help.

**Comment by hackpointt** [comment] 2023-05-07 15:46
same problem

**Comment by osanseviero** [comment] 2023-05-08 09:53
Doing this worked for me

```
sudo apt-get install -y python-opengl
```

**Comment by hackpointt** [comment] 2023-05-08 10:10
I got though this
in ubuntu 22, install comand should be:

`sudo apt-get install -y python3-opengl`

**Comment by mrvincenzo** [comment] 2023-07-23 18:03
@simoninithomas Why was it closed? The issue is still reproducible when running in Colab. In Unit 2, it is even worse, since the command is `!apt install python-opengl ffmpeg xvfb`. Since it fails on installing `python-opengl`, it doesn't install the other packages, `ffmpeg` and `xvfb`, which in turn leads to 

`No such file or directory: 'Xvfb'`
when trying to run the following cell
```
# Virtual display
from pyvirtualdisplay import Display

virtual_display = Display(visible=0, size=(1400, 900))
virtual_display.start()
```

**Comment by simoninithomas** [comment] 2023-08-08 09:26
@mrvincenzo my appologies it was a mistake. I updated the notebook some weeks ago and I forgot to push it to to the github repo.

**Comment by simoninithomas** [comment] 2023-08-08 09:32
The update is done ✅ Thanks for pointing this out. And my apologies for the closing mistake 🤗

**Closed** 2023-08-08 11:44 UTC

**Comment by nosark** [comment] 2023-12-29 05:25
> I got though this in ubuntu 22, install comand should be:
> 
> `sudo apt-get install -y python3-opengl`

this worked for me, thanks!
